### ISSUE TITLE
Any interest in making this work with the newer mu4e gnus message view?

### ISSUE THREAD

**Issue by dschwilk** [gambhiro/mu4e-detach#1]
It looks like the detach code is all tightly linked to the old mu4e message view. Any interest in making it work with the gnus message view using the newer mu4e-view-mime-part-actions? 

https://www.djcbsoftware.nl/code/mu/mu4e/MSGV-Actions.html

**Comment by gambhiro** [comment]
Not really. This was an old idea and it's probably better to remove this repo.
